name: Benchmarks Reusable

on:
  workflow_call:
    inputs:
      str_name:
        required: true
        type: string
      unit:
        required: true
        type: string
      pr_no:
        required: true
        # even though this is a number, this is a workaround for issues with
        # reusable workflow calls that result in "Unexpected value '0'" error.
        type: string
      bench_script_params:
        required: false
        type: string
        default: ''
      sycl_config_params:
        required: false
        type: string
        default: ''
      sycl_repo:
        required: true
        type: string
        default: 'intel/llvm'
      sycl_commit:
        required: false
        type: string
        default: ''
      upload_report:
        required: false
        type: boolean
        default: false

permissions:
  contents: read
  pull-requests: write

jobs:
  e2e-build-hw:
    name: Build SYCL, UR, run Compute Benchmarks
    strategy:
      matrix:
        adapter: [
          {str_name: "${{ inputs.str_name }}",
          sycl_config: "${{ inputs.sycl_config_params }}",
          unit: "${{ inputs.unit }}"
          }
        ]
        build_type: [Release]
        compiler: [{c: clang, cxx: clang++}]

    runs-on: ubuntu-latest

    steps:
    - name: Cleanup self-hosted workspace
      if: always()
      run: |
        ls -la ./
        rm -rf ./* || true

    - name: Add comment to PR
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      if: ${{ always() && inputs.pr_no != 0 }}
      with:
        script: |
          const pr_no = '${{ inputs.pr_no }}';
          const adapter = '${{ matrix.adapter.str_name }}';
          const url = '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}';
          const params = '${{ inputs.bench_script_params }}';
          const body = `Compute Benchmarks ${adapter} run (with params: ${params}):\n${url}`;

          github.rest.issues.createComment({
            issue_number: pr_no,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: body
          })

    - name: Checkout UR
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        path: ur-repo

    - name: Install pip packages
      run: |
        pip install --force-reinstall -r ${{github.workspace}}/ur-repo/third_party/benchmark_requirements.txt

    # We need to fetch special ref for proper PR's merge commit. Note, this ref may be absent if the PR is already merged.

    # REMOVE start
    # - name: Fetch PR's merge commit
    #   if: ${{ inputs.pr_no != 0 }}
    #   working-directory: ${{github.workspace}}/ur-repo
    #   env:
    #     PR_NO: ${{ inputs.pr_no }}
    #   run: |
    #     git fetch -- https://github.com/${{github.repository}} +refs/pull/${PR_NO}/*:refs/remotes/origin/pr/${PR_NO}/*
    #     git checkout origin/pr/${PR_NO}/merge
    #     git rev-parse origin/pr/${PR_NO}/merge

# HERE
    - name: Install HWLOC
      run: |
        sudo apt-get update
        sudo apt-get install libhwloc-dev

    - name: Checkout UMF
      uses: actions/checkout@71527f55b22e76ad1966b9e2ba09e788d0975b12 # v4.1.1
      with:
        repository: EuphoricThinking/unified-memory-framework
        ref: 162853b6298a7b65b3c0d0501ca12ae53bc4d9c7
        path: umf-repo
        fetch-depth: 1
        fetch-tags: false

    - name: Configure UMF
      run: >
        cmake -DCMAKE_BUILD_TYPE=Release
        -S${{github.workspace}}/umf-repo
        -B${{github.workspace}}/umf_build
        -DUMF_BUILD_BENCHMARKS=ON
        -DUMF_TESTS_FAIL_ON_SKIP=ON

    - name: Build UR
      run: cmake --build ${{github.workspace}}/umf_build -j $(nproc)

    #   # remove end

    # - name: Install UR
    #   run: cmake --install ${{github.workspace}}/ur_build

    # numactl -N 0 

    - name: Run benchmarks
      working-directory: ${{ github.workspace }}/umf-repo/
      id: benchmarks
      run: >
        ${{ github.workspace }}/umf-repo/scripts/benchmarks/main.py
        ~/bench_workdir
        --umf ${{ github.workspace }}/umf_build
        ${{ inputs.upload_report && '--output-html' || '' }}
        ${{ inputs.bench_script_params }}

    - name: Add comment to PR
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      if: ${{ always() && inputs.pr_no != 0 }}
      with:
        script: |
          let markdown = ""
          try {
            const fs = require('fs');
            markdown = fs.readFileSync('ur-repo/benchmark_results.md', 'utf8');
          } catch(err) {
          }

          const pr_no = '${{ inputs.pr_no }}';
          const adapter = '${{ matrix.adapter.str_name }}';
          const url = '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}';
          const test_status = '${{ steps.benchmarks.outcome }}';
          const job_status = '${{ job.status }}';
          const params = '${{ inputs.bench_script_params }}';
          const body = `Compute Benchmarks ${adapter} run (${params}):\n${url}\nJob status: ${job_status}. Test status: ${test_status}.\n ${markdown}`;

          github.rest.issues.createComment({
            issue_number: pr_no,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: body
          })

    - name: Upload HTML report
      if: ${{ always() && inputs.upload_report }}
      uses: actions/cache/save@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4.1.2
      with:
        path: umf-repo/benchmark_results.html
        key: benchmark-results-${{ matrix.adapter.str_name }}-${{ github.run_id }}
